language: cpp
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install openjdk-7-jdk
  - sudo apt-get install gcc-multilib mingw32-binutils
  - sudo apt-get install git gnupg flex bison gperf build-essential
  - sudo apt-get install zip curl libc6-dev libncurses5-dev:i386
  - sudo apt-get install x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386
  - sudo apt-get install libgl1-mesa-dev g++-multilib mingw32 tofrodos
  - sudo apt-get install python-markdown libxml2-utils xsltproc zlib1g-dev:i386
  - sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
before_script:
  - export USE_CCACHE=1
  - mkdir -p ~/bin
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - mkdir -p lollipop
  - cd lollipop
  - git config --global user.email "travisci@gocanarytel.com"
  - git config --global user.name "Travis CI"
  - git config --global color.branch auto
  - git config --global color.diff auto
  - git config --global color.interactive auto
  - git config --global color.status auto
  - repo init -u https://github.com/CyanogenMod/android.git -b cm-12.1
  - repo sync -j8
  - git clone git@github.com:TheMuppets/proprietary_vendor_huawei.git vendor/huawei
  - source build/envsetup.sh
  - lunch cm_mt2-userdebug
  - mka bacon
